arangodb.spring.data.database=MULTI_RCA
arangodb.spring.data.user=root
arangodb.spring.data.password=71325
arangodb.spring.data.hosts=192.168.72.128:8529
arangodb.spring.data.returnOriginalEntities=false
#logging.level.com.arangodb.internal.net.Communication=DEBUG
