server:
  port: 8085
  address: 0.0.0.0
  data:
    arangodb:
      hosts:
        - 192.168.72.128:8529
      user: root
      password: 71325
      database: MULTI_RCA

spring:
  application:
    name: rca-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cache:
    cache-names: rca
  profiles:
    active: production

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
